internal object Versions{
    const val ANDROIDX_CORE_KTX = "1.9.0"
    const val ANDROIDX_LIFECYCLE_RUNTIME_KTX = "2.6.1"
    const val ANDROIDX_ACTIVITY_COMPOSE = "1.7.0"
    const val ANDROIDX_COMPOSE_BOM= "2023.03.00"
    const val ANDROIDX_COMPOSE_UI= "+"
    const val ANDROIDX_COMPOSE_UI_GRAPHICS= "+"
    const val ANDROIDX_COMPOSE_UI_TOOLING_PREVIEW= "+"
    const val ANDROIDX_COMPOSE_MATERIAL3= "+"
    const val GRADLE_SECRETS_PLUGINS= "2.0.1"
    const val PLAY_SERVICES_MAPS= "18.1.0"
    const val PLAY_SERVICES_LOCATION= "21.0.1"
    const val MAPS_COMPOSE= "2.8.0"
    const val MAPS_KTX= "3.2.1"
    const val MAPS_UTILS_KTX= "3.2.1"
    const val APOLLO_RUNTIME= "3.8.2"
    const val GRADLE_BUILD= "7.1.0"
    const val KOTLIN_GRADLE_PLUGIN= "1.7.0"
    const val LIFECYCLE_VIEWMODEL_COMPOSE= "2.6.2"
    const val NAVIGATION_COMPOSE= "2.7.4"
    const val FIREBASE_BOM= "32.4.0"
    const val PLAY_SERVICES_AUTH= "20.7.0"
    const val COIL_COMPOSE= "2.2.2"

    // TODO: Add test dependencies here as well
}